### PR TITLE
Added a google services file replacer

### PR DESCRIPTION
**Pull request by jimbobbennett**
Added a pre-build script to update the contents of a google-services.json file.

This is a bit different to other examples with a simple find/replace as it needs to remove escape characters - the Json that comes from the env var is full of \" which need to be replaced with ".

### CODE REVIEW

**Comment by jimbobbennett** [comment]
Wasn't sure on the file location, so please advise if there is a better place to put this. This is applicable to all Android apps.

**Comment by derpixeldan** [comment]
That's awesome, can you please add it to the TOC in the README.md?

**Comment by jimbobbennett** [comment]
@derpixeldan - done!

**Comment by derpixeldan** [comment]
@jimbobbennett 🙌

**Pull request merged**
